platform :osx, '11.0'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
